task:
  arm_container:
    image: ubuntu:20.04

  environment:
    CONAN_USER_HOME: /root/.conan2

  checkout_script:
    - git clone https://github.com/AndreaCicca/SHA-implementation .
    - git checkout main

  setup_script:
    # Installa Conan
    - sudo apt update
    - sudo apt install -y python3-pip
    - pip3 install conan

  install_script:
    # Crea il profilo di Conan e directory build
    - conan profile detect --force
    - mkdir -p src/build

  build_script:
    # Installa le dipendenze con Conan e build con CMake
    - conan install src --output-folder=src/build --build=missing
    - cmake -S src -B src/build --preset conan-release
    - cmake --build src/build
