name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Conan
      uses: jwidauer/setup-conan@v1

    - name: Create build directory
      run: mkdir build

    - name: Install dependencies
      run: conan install . --output-folder=build --build=missing

    - name: Configure CMake
      run: cmake -S . -B build --preset conan-release

    - name: Build
      run: cmake --build build
