name: Cmake compilation Conan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Conan
      uses: jwidauer/setup-conan@v1

    - name: Cache Conan packages
      id: cache-conan
      uses: actions/cache@v3
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-conan2-${{ hashFiles('src/conanfile.txt') }}
        restore-keys: |
          ${{ runner.os }}-conan2-

    - name: Create default Conan profile
      run: conan profile detect --force

    - name: Create build directory
      run: mkdir -p src/build

    - name: Install dependencies
      run: conan install src --output-folder=src/build --build=missing

    - name: Configure CMake
      run: cmake -S src -B src/build --preset conan-release

    - name: Build
      run: cmake --build src/build

    - name: Pull pdflatex docker image
      run: docker pull andreacicca/pdflatex:latest
    
    - name: Generate pdf
      run: docker run -it --rm -v "${PWD}:/root/shared/folder" --name pdflatex pdflatex main.tex
