name: Generate Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Documentation
      uses: mattnotmitt/doxygen-action@v1.9.5
      with:
        working-directory: 'src'
        doxyfile-path: 'Doxyfile'
        enable-latex: true
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Documentation
        path: src/latex/main.pdf