name: PDF compilation via Latex

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Move to the directory containing the main.tex file
      run: cd latex

    - name: Pull pdflatex docker image
      run: docker pull andreacicca/pdflatex:latest

    - name: Generate pdf
      run: docker run --rm -v "${PWD}:/root/shared/folder" --name pdflatex andreacicca/pdflatex main.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: ./main.pdf